import './var.css';
export { Application } from './components/Application';
export { ApplicationArrange } from './components/ApplicationArrange';
export { ConfigProvider } from './components/ConfigProvider';
export { Portal, FileList, useChatFile, FilePreview, usePCMPlayer, useVoiceToText, InputBoxToolbar } from '@xm/ai.kit.base';
export { Chat } from './components/Chat';
export { ResultTTSAction } from './components/Chat/ResultTTSAction';
export { useChat } from './components/Chat/hooks/useChat';
export { History } from './components/History';
export { HistorySide } from './components/HistorySide';
export { DrawerFilePreview } from './components/DrawerFilePreview';
